
package edu.udistrital.client.model;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-15T15:10:31.056-05:00
 * Generated source version: 3.1.5
 * 
 */
public final class Calculadora_CalculadoraPort_Client {

    private static final QName SERVICE_NAME = new QName("http://model.udistrital.edu/", "CalculadoraService");

    private Calculadora_CalculadoraPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalculadoraService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalculadoraService ss = new CalculadoraService(wsdlURL, SERVICE_NAME);
        Calculadora port = ss.getCalculadoraPort();  
        
        {
        System.out.println("Invoking sumar...");
        int _sumar_numero1 = 148870870;
        int _sumar_numero2 = -1061687735;
        int _sumar__return = port.sumar(_sumar_numero1, _sumar_numero2);
        System.out.println("sumar.result=" + _sumar__return);


        }

        System.exit(0);
    }

}
