package edu.udistrital.client.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-15T15:10:31.103-05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://model.udistrital.edu/", name = "Calculadora")
@XmlSeeAlso({ObjectFactory.class})
public interface Calculadora {

    @WebResult(name = "Resultado", targetNamespace = "")
    @RequestWrapper(localName = "Sumar", targetNamespace = "http://model.udistrital.edu/", className = "edu.udistrital.client.model.Sumar")
    @WebMethod(operationName = "Sumar")
    @ResponseWrapper(localName = "SumarResponse", targetNamespace = "http://model.udistrital.edu/", className = "edu.udistrital.client.model.SumarResponse")
    public int sumar(
        @WebParam(name = "Numero1", targetNamespace = "")
        int numero1,
        @WebParam(name = "Numero2", targetNamespace = "")
        int numero2
    );
}
